### ISSUE TITLE
Validation of Inverse Kinematics

### ISSUE THREAD

**Issue by Elektron97** [RO-Projects/scara#13]
I checked your code, well done. Maybe, it's useful to understand the error with the ideal model of the robot (siciliano) and the simulated robot in gazebo. You can use: 
- [x]  First you can use the Ground Truth data from Gazebo and compare the results.
- [x]  Second, you can use a closed loop inverse kinematic algorithm (CLIK) with sensor information.

Note that, the CLIK algorithm is also a kinematic controller.

**Comment by bademeister99** [comment]
![grafik](https://user-images.githubusercontent.com/123369589/218150441-d51f899f-cc85-40cd-94db-2410a3a1b0f0.png)
OpenLoop Inverse Kinematics validatet. The Plot shows the error (upper window) as well as the positions in space (lower window) while the robot is repetitively following a trajectory of 5 points. The error converges to zero; if smaller than 0.0005, the next desired position is published.
